spring.application.name=meveum

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/meveum
spring.datasource.username=meveum
spring.datasource.password=meveum

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.public.key=classpath:authz.pub
jwt.private.key=classpath:authz.pem
